version: "3.8"

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: mateuszkowalke
      POSTGRES_PASSWORD: Kowalkem2@
      POSTGRES_DB: muzyka_niezalezna
    ports:
      - 5432:5432

  muzyka_niezalezna:
    build:
      context: .
    volumes:
      - ./:/usr/app
    ports:
      - 8000:8000
    # environment:
    #     DB_CONNECTION: pg
    #     DB_HOST: db ## same as the database service name
    #     DB_PORT: 5432
    #     DB_USER: mateuszkowalke
    #     DB_DATABASE: muzyka_niezalezna
    #     DB_PASSWORD: 63eaQB9wtLqmNBpg
