# Generated by Django 3.0.8 on 2020-07-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_repo', '0002_auto_20200716_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='artists',
        ),
        migrations.AlterField(
            model_name='cover',
            name='large',
            field=models.FileField(upload_to='tests'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='medium',
            field=models.FileField(upload_to='tests'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='small',
            field=models.FileField(upload_to='tests'),
        ),
    ]
