# Generated by Django 3.0.8 on 2020-07-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_repo', '0003_auto_20200724_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='albums',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='artists',
        ),
    ]
