# Generated by Django 3.1 on 2020-08-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_repo', '0005_auto_20200724_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cover',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={},
        ),
        migrations.AlterField(
            model_name='song',
            name='albums',
            field=models.ManyToManyField(blank=True, to='song_repo.Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(blank=True, to='song_repo.Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='songs'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(blank=True, to='song_repo.Genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(default='aaa', max_length=128),
            preserve_default=False,
        ),
    ]
