# Generated by Django 3.1 on 2020-08-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_repo', '0008_auto_20200810_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, to='song_repo.Song'),
        ),
    ]
